{{- $certManager := .Values.certManager -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $certManager.clusterIssuer.route53.secretName }}
  namespace: {{ $certManager.namespace }}
type: Opaque
stringData:
  access-key-id: {{ $certManager.clusterIssuer.route53.accessKeyId | quote }}
  secret-access-key: {{ $certManager.clusterIssuer.route53.secretAccessKey | quote }}
